name: Pipeline
on:
  push:
    tags-ignore:
      - v*
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
      TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_CACHE_SIZE: ${{ secrets.DB_CACHE_SIZE }}
          envkey_DB_CACHE_TTL: ${{ secrets.DB_CACHE_TTL }}
          envkey_DB_MAX_ROW_COUNT_FOR_CACHE: ${{ secrets.DB_MAX_ROW_COUNT_FOR_CACHE }}
          envkey_FILES_DIR: ${{ secrets.FILES_DIR }}
          envkey_MAX_USERS_ONLINE: ${{ secrets.MAX_USERS_ONLINE }}
          envkey_TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          envkey TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          directory: '.'
          fail_on_empty: true

      - name: Set up Python 3.9.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.9

      - name: Install dependencies
        run: |
          pip3 install -r requirements-dev.txt

      - name: Run linter
        run: flake8 . --count --show-source --statistics

      - name: Run tests
        run: python -m pytest
